/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -no-gen-example`
 */

#ifndef	_CE_ModeBRestricted_H_
#define	_CE_ModeBRestricted_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CE_ModeBRestricted {
	CE_ModeBRestricted_restricted	= 0,
	CE_ModeBRestricted_not_restricted	= 1
	/*
	 * Enumeration is extensible
	 */
} e_CE_ModeBRestricted;

/* CE-ModeBRestricted */
typedef long	 CE_ModeBRestricted_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CE_ModeBRestricted;
asn_struct_free_f CE_ModeBRestricted_free;
asn_struct_print_f CE_ModeBRestricted_print;
asn_constr_check_f CE_ModeBRestricted_constraint;
ber_type_decoder_f CE_ModeBRestricted_decode_ber;
der_type_encoder_f CE_ModeBRestricted_encode_der;
xer_type_decoder_f CE_ModeBRestricted_decode_xer;
xer_type_encoder_f CE_ModeBRestricted_encode_xer;
oer_type_decoder_f CE_ModeBRestricted_decode_oer;
oer_type_encoder_f CE_ModeBRestricted_encode_oer;
per_type_decoder_f CE_ModeBRestricted_decode_uper;
per_type_encoder_f CE_ModeBRestricted_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CE_ModeBRestricted_H_ */
#include <asn_internal.h>
