/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -no-gen-example`
 */

#ifndef	_ConnectedengNBList_H_
#define	_ConnectedengNBList_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ConnectedengNBItem;

/* ConnectedengNBList */
typedef struct ConnectedengNBList {
	A_SEQUENCE_OF(struct ConnectedengNBItem) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectedengNBList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectedengNBList;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ConnectedengNBItem.h"

#endif	/* _ConnectedengNBList_H_ */
#include <asn_internal.h>
