/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -no-gen-example`
 */

#ifndef	_EDT_Session_H_
#define	_EDT_Session_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EDT_Session {
	EDT_Session_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_EDT_Session;

/* EDT-Session */
typedef long	 EDT_Session_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EDT_Session;
asn_struct_free_f EDT_Session_free;
asn_struct_print_f EDT_Session_print;
asn_constr_check_f EDT_Session_constraint;
ber_type_decoder_f EDT_Session_decode_ber;
der_type_encoder_f EDT_Session_encode_der;
xer_type_decoder_f EDT_Session_decode_xer;
xer_type_encoder_f EDT_Session_encode_xer;
oer_type_decoder_f EDT_Session_decode_oer;
oer_type_encoder_f EDT_Session_encode_oer;
per_type_decoder_f EDT_Session_decode_uper;
per_type_encoder_f EDT_Session_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EDT_Session_H_ */
#include <asn_internal.h>
