/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_CE_ModeBRestricted_H_
#define	_CE_ModeBRestricted_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CE_ModeBRestricted {
	CE_ModeBRestricted_restricted	= 0,
	CE_ModeBRestricted_not_restricted	= 1
	/*
	 * Enumeration is extensible
	 */
} e_CE_ModeBRestricted;

/* CE-ModeBRestricted */
typedef long	 CE_ModeBRestricted_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CE_ModeBRestricted_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CE_ModeBRestricted;
extern const asn_INTEGER_specifics_t asn_SPC_CE_ModeBRestricted_specs_1;
asn_struct_free_f CE_ModeBRestricted_free;
asn_struct_print_f CE_ModeBRestricted_print;
asn_constr_check_f CE_ModeBRestricted_constraint;
xer_type_decoder_f CE_ModeBRestricted_decode_xer;
xer_type_encoder_f CE_ModeBRestricted_encode_xer;
jer_type_encoder_f CE_ModeBRestricted_encode_jer;
per_type_decoder_f CE_ModeBRestricted_decode_aper;
per_type_encoder_f CE_ModeBRestricted_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _CE_ModeBRestricted_H_ */
#include <asn_internal.h>
