/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_E_RABToBeSwitchedDLList_H_
#define	_E_RABToBeSwitchedDLList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "E-RAB-IE-ContainerList.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E-RABToBeSwitchedDLList */
typedef E_RAB_IE_ContainerList_1280P4_t	 E_RABToBeSwitchedDLList_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_E_RABToBeSwitchedDLList_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_E_RABToBeSwitchedDLList;
asn_struct_free_f E_RABToBeSwitchedDLList_free;
asn_struct_print_f E_RABToBeSwitchedDLList_print;
asn_constr_check_f E_RABToBeSwitchedDLList_constraint;
xer_type_decoder_f E_RABToBeSwitchedDLList_decode_xer;
xer_type_encoder_f E_RABToBeSwitchedDLList_encode_xer;
jer_type_encoder_f E_RABToBeSwitchedDLList_encode_jer;
per_type_decoder_f E_RABToBeSwitchedDLList_decode_aper;
per_type_encoder_f E_RABToBeSwitchedDLList_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _E_RABToBeSwitchedDLList_H_ */
#include <asn_internal.h>
