/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_EARFCN_H_
#define	_EARFCN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* EARFCN */
typedef long	 EARFCN_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EARFCN_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EARFCN;
asn_struct_free_f EARFCN_free;
asn_struct_print_f EARFCN_print;
asn_constr_check_f EARFCN_constraint;
xer_type_decoder_f EARFCN_decode_xer;
xer_type_encoder_f EARFCN_encode_xer;
jer_type_encoder_f EARFCN_encode_jer;
per_type_decoder_f EARFCN_decode_aper;
per_type_encoder_f EARFCN_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EARFCN_H_ */
#include <asn_internal.h>
