/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_En_gNB_ID_H_
#define	_En_gNB_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* En-gNB-ID */
typedef BIT_STRING_t	 En_gNB_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_En_gNB_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_En_gNB_ID;
asn_struct_free_f En_gNB_ID_free;
asn_struct_print_f En_gNB_ID_print;
asn_constr_check_f En_gNB_ID_constraint;
xer_type_decoder_f En_gNB_ID_decode_xer;
xer_type_encoder_f En_gNB_ID_encode_xer;
jer_type_encoder_f En_gNB_ID_encode_jer;
per_type_decoder_f En_gNB_ID_decode_aper;
per_type_encoder_f En_gNB_ID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _En_gNB_ID_H_ */
#include <asn_internal.h>
