/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_Ethernet_Type_H_
#define	_Ethernet_Type_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ethernet_Type {
	Ethernet_Type_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_Ethernet_Type;

/* Ethernet-Type */
typedef long	 Ethernet_Type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Ethernet_Type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Ethernet_Type;
extern const asn_INTEGER_specifics_t asn_SPC_Ethernet_Type_specs_1;
asn_struct_free_f Ethernet_Type_free;
asn_struct_print_f Ethernet_Type_print;
asn_constr_check_f Ethernet_Type_constraint;
xer_type_decoder_f Ethernet_Type_decode_xer;
xer_type_encoder_f Ethernet_Type_encode_xer;
jer_type_encoder_f Ethernet_Type_encode_jer;
per_type_decoder_f Ethernet_Type_decode_aper;
per_type_encoder_f Ethernet_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Ethernet_Type_H_ */
#include <asn_internal.h>
