/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_ExpectedActivityPeriod_H_
#define	_ExpectedActivityPeriod_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ExpectedActivityPeriod */
typedef long	 ExpectedActivityPeriod_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ExpectedActivityPeriod_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ExpectedActivityPeriod;
asn_struct_free_f ExpectedActivityPeriod_free;
asn_struct_print_f ExpectedActivityPeriod_print;
asn_constr_check_f ExpectedActivityPeriod_constraint;
xer_type_decoder_f ExpectedActivityPeriod_decode_xer;
xer_type_encoder_f ExpectedActivityPeriod_encode_xer;
jer_type_encoder_f ExpectedActivityPeriod_encode_jer;
per_type_decoder_f ExpectedActivityPeriod_decode_aper;
per_type_encoder_f ExpectedActivityPeriod_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ExpectedActivityPeriod_H_ */
#include <asn_internal.h>
