/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#include "MDTMode-Extension.h"

/*
 * This type is implemented using ProtocolIE_SingleContainer_8146P19,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_MDTMode_Extension_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_MDTMode_Extension = {
	"MDTMode-Extension",
	"MDTMode-Extension",
	&asn_OP_SEQUENCE,
	asn_DEF_MDTMode_Extension_tags_1,
	sizeof(asn_DEF_MDTMode_Extension_tags_1)
		/sizeof(asn_DEF_MDTMode_Extension_tags_1[0]), /* 1 */
	asn_DEF_MDTMode_Extension_tags_1,	/* Same as above */
	sizeof(asn_DEF_MDTMode_Extension_tags_1)
		/sizeof(asn_DEF_MDTMode_Extension_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_MDTMode_ExtensionIE_77,
	3,	/* Elements count */
	&asn_SPC_MDTMode_ExtensionIE_specs_77	/* Additional specs */
};

