/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_MDTMode_Extension_H_
#define	_MDTMode_Extension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-SingleContainer.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MDTMode-Extension */
typedef ProtocolIE_SingleContainer_8146P19_t	 MDTMode_Extension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MDTMode_Extension;
asn_struct_free_f MDTMode_Extension_free;
asn_struct_print_f MDTMode_Extension_print;
asn_constr_check_f MDTMode_Extension_constraint;
xer_type_decoder_f MDTMode_Extension_decode_xer;
xer_type_encoder_f MDTMode_Extension_encode_xer;
jer_type_encoder_f MDTMode_Extension_encode_jer;
per_type_decoder_f MDTMode_Extension_decode_aper;
per_type_encoder_f MDTMode_Extension_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _MDTMode_Extension_H_ */
#include <asn_internal.h>
