/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-Containers"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#include "ProtocolIE-SingleContainer.h"

/*
 * This type is implemented using E_RABToBeSetupItemBearerSUReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABSetupItemBearerSUResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeModifiedItemBearerModReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABModifyItemBearerModResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABReleaseItemBearerRelCompIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeSetupItemCtxtSUReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABSetupItemCtxtSUResIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using TAIItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using UE_associatedLogicalS1_ConnectionItemRes,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using UE_associatedLogicalS1_ConnectionItemResAck,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABModifyItemBearerModConfIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Bearers_SubjectToStatusTransfer_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using Bearers_SubjectToEarlyStatusTransfer_ItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using DAPSResponseInfoListIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABInformationListIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABSecurityResultListIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABUsageReportItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using EventTrigger_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using MDTMode_ExtensionIE,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using MeasurementThresholdL1LoggedMDT_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RecommendedCellItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using RecommendedENBItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using SecondaryRATDataUsageReportItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using SensorNameConfig_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using SONInformation_ExtensionIE,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using SourceNodeID_ExtensionIE,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABDataForwardingItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeSetupItemHOReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABAdmittedItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABFailedtoSetupItemHOReqAckIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeSwitchedDLItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeSwitchedULItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeUpdatedItemIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABToBeModifiedItemBearerModIndIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABNotToBeModifiedItemBearerModIndIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABFailedToResumeItemResumeReqIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using E_RABFailedToResumeItemResumeResIEs,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P0 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P0_tags_1,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P0_tags_1[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P0_tags_1)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P0_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSetupItemBearerSUReqIEs_1,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSetupItemBearerSUReqIEs_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P1 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P1_tags_2,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P1_tags_2[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P1_tags_2)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P1_tags_2[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABSetupItemBearerSUResIEs_5,
	3,	/* Elements count */
	&asn_SPC_E_RABSetupItemBearerSUResIEs_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P2 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P2_tags_3,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P2_tags_3[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P2_tags_3)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P2_tags_3[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeModifiedItemBearerModReqIEs_9,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeModifiedItemBearerModReqIEs_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P3 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P3_tags_4,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P3_tags_4[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P3_tags_4)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P3_tags_4[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABModifyItemBearerModResIEs_13,
	3,	/* Elements count */
	&asn_SPC_E_RABModifyItemBearerModResIEs_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P4 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P4_tags_5,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P4_tags_5[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P4_tags_5)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P4_tags_5[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABReleaseItemBearerRelCompIEs_17,
	3,	/* Elements count */
	&asn_SPC_E_RABReleaseItemBearerRelCompIEs_specs_17	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P5 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P5_tags_6,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P5_tags_6[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P5_tags_6)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P5_tags_6[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSetupItemCtxtSUReqIEs_21,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSetupItemCtxtSUReqIEs_specs_21	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P6 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P6_tags_7,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P6_tags_7[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P6_tags_7)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P6_tags_7[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABSetupItemCtxtSUResIEs_25,
	3,	/* Elements count */
	&asn_SPC_E_RABSetupItemCtxtSUResIEs_specs_25	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P7 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P7_tags_8,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P7_tags_8[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P7_tags_8)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P7_tags_8[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_TAIItemIEs_29,
	3,	/* Elements count */
	&asn_SPC_TAIItemIEs_specs_29	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P8 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P8_tags_9,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P8_tags_9[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P8_tags_9)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P8_tags_9[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UE_associatedLogicalS1_ConnectionItemRes_33,
	3,	/* Elements count */
	&asn_SPC_UE_associatedLogicalS1_ConnectionItemRes_specs_33	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P9 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P9_tags_10,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P9_tags_10[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P9_tags_10)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P9_tags_10[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UE_associatedLogicalS1_ConnectionItemResAck_37,
	3,	/* Elements count */
	&asn_SPC_UE_associatedLogicalS1_ConnectionItemResAck_specs_37	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P10_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P10 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P10_tags_11,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P10_tags_11[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P10_tags_11,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P10_tags_11)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P10_tags_11[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABModifyItemBearerModConfIEs_41,
	3,	/* Elements count */
	&asn_SPC_E_RABModifyItemBearerModConfIEs_specs_41	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P11_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P11 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P11_tags_12,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P11_tags_12[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P11_tags_12,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P11_tags_12)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P11_tags_12[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Bearers_SubjectToStatusTransfer_ItemIEs_45,
	3,	/* Elements count */
	&asn_SPC_Bearers_SubjectToStatusTransfer_ItemIEs_specs_45	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P12_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P12 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P12_tags_13,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P12_tags_13[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P12_tags_13,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P12_tags_13)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P12_tags_13[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Bearers_SubjectToEarlyStatusTransfer_ItemIEs_49,
	3,	/* Elements count */
	&asn_SPC_Bearers_SubjectToEarlyStatusTransfer_ItemIEs_specs_49	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P13_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P13 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P13_tags_14,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P13_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P13_tags_14[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P13_tags_14,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P13_tags_14)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P13_tags_14[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_DAPSResponseInfoListIEs_53,
	3,	/* Elements count */
	&asn_SPC_DAPSResponseInfoListIEs_specs_53	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P14_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P14 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P14_tags_15,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P14_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P14_tags_15[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P14_tags_15,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P14_tags_15)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P14_tags_15[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABInformationListIEs_57,
	3,	/* Elements count */
	&asn_SPC_E_RABInformationListIEs_specs_57	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P15_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P15 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P15_tags_16,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P15_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P15_tags_16[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P15_tags_16,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P15_tags_16)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P15_tags_16[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABItemIEs_61,
	3,	/* Elements count */
	&asn_SPC_E_RABItemIEs_specs_61	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P16_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P16 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P16_tags_17,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P16_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P16_tags_17[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P16_tags_17,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P16_tags_17)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P16_tags_17[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABSecurityResultListIEs_65,
	3,	/* Elements count */
	&asn_SPC_E_RABSecurityResultListIEs_specs_65	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P17_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P17 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P17_tags_18,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P17_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P17_tags_18[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P17_tags_18,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P17_tags_18)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P17_tags_18[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABUsageReportItemIEs_69,
	3,	/* Elements count */
	&asn_SPC_E_RABUsageReportItemIEs_specs_69	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P18_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P18 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P18_tags_19,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P18_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P18_tags_19[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P18_tags_19,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P18_tags_19)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P18_tags_19[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_EventTrigger_ExtIEs_73,
	3,	/* Elements count */
	&asn_SPC_EventTrigger_ExtIEs_specs_73	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P19_tags_20[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P19 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P19_tags_20,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P19_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P19_tags_20[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P19_tags_20,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P19_tags_20)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P19_tags_20[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_MDTMode_ExtensionIE_77,
	3,	/* Elements count */
	&asn_SPC_MDTMode_ExtensionIE_specs_77	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P20_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P20 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P20_tags_21,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P20_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P20_tags_21[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P20_tags_21,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P20_tags_21)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P20_tags_21[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_MeasurementThresholdL1LoggedMDT_ExtIEs_81,
	3,	/* Elements count */
	&asn_SPC_MeasurementThresholdL1LoggedMDT_ExtIEs_specs_81	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P21_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P21 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P21_tags_22,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P21_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P21_tags_22[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P21_tags_22,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P21_tags_22)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P21_tags_22[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RecommendedCellItemIEs_85,
	3,	/* Elements count */
	&asn_SPC_RecommendedCellItemIEs_specs_85	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P22_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P22 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P22_tags_23,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P22_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P22_tags_23[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P22_tags_23,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P22_tags_23)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P22_tags_23[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RecommendedENBItemIEs_89,
	3,	/* Elements count */
	&asn_SPC_RecommendedENBItemIEs_specs_89	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P23_tags_24[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P23 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P23_tags_24,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P23_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P23_tags_24[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P23_tags_24,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P23_tags_24)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P23_tags_24[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SecondaryRATDataUsageReportItemIEs_93,
	3,	/* Elements count */
	&asn_SPC_SecondaryRATDataUsageReportItemIEs_specs_93	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P24_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P24 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P24_tags_25,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P24_tags_25)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P24_tags_25[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P24_tags_25,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P24_tags_25)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P24_tags_25[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SensorNameConfig_ExtIEs_97,
	3,	/* Elements count */
	&asn_SPC_SensorNameConfig_ExtIEs_specs_97	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P25_tags_26[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P25 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P25_tags_26,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P25_tags_26)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P25_tags_26[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P25_tags_26,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P25_tags_26)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P25_tags_26[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SONInformation_ExtensionIE_101,
	3,	/* Elements count */
	&asn_SPC_SONInformation_ExtensionIE_specs_101	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P26_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P26 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P26_tags_27,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P26_tags_27)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P26_tags_27[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P26_tags_27,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P26_tags_27)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P26_tags_27[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_SourceNodeID_ExtensionIE_105,
	3,	/* Elements count */
	&asn_SPC_SourceNodeID_ExtensionIE_specs_105	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P27_tags_28[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P27 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P27_tags_28,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P27_tags_28)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P27_tags_28[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P27_tags_28,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P27_tags_28)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P27_tags_28[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABDataForwardingItemIEs_497,
	3,	/* Elements count */
	&asn_SPC_E_RABDataForwardingItemIEs_specs_497	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P28_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P28 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P28_tags_29,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P28_tags_29)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P28_tags_29[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P28_tags_29,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P28_tags_29)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P28_tags_29[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSetupItemHOReqIEs_501,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSetupItemHOReqIEs_specs_501	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P29_tags_30[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P29 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P29_tags_30,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P29_tags_30)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P29_tags_30[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P29_tags_30,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P29_tags_30)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P29_tags_30[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABAdmittedItemIEs_505,
	3,	/* Elements count */
	&asn_SPC_E_RABAdmittedItemIEs_specs_505	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P30_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P30 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P30_tags_31,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P30_tags_31)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P30_tags_31[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P30_tags_31,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P30_tags_31)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P30_tags_31[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABFailedtoSetupItemHOReqAckIEs_509,
	3,	/* Elements count */
	&asn_SPC_E_RABFailedtoSetupItemHOReqAckIEs_specs_509	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P31_tags_32[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P31 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P31_tags_32,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P31_tags_32)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P31_tags_32[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P31_tags_32,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P31_tags_32)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P31_tags_32[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSwitchedDLItemIEs_513,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSwitchedDLItemIEs_specs_513	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P32_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P32 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P32_tags_33,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P32_tags_33)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P32_tags_33[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P32_tags_33,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P32_tags_33)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P32_tags_33[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeSwitchedULItemIEs_517,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeSwitchedULItemIEs_specs_517	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P33_tags_34[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P33 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P33_tags_34,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P33_tags_34)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P33_tags_34[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P33_tags_34,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P33_tags_34)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P33_tags_34[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeUpdatedItemIEs_521,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeUpdatedItemIEs_specs_521	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P34_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P34 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P34_tags_35,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P34_tags_35)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P34_tags_35[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P34_tags_35,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P34_tags_35)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P34_tags_35[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABToBeModifiedItemBearerModIndIEs_525,
	3,	/* Elements count */
	&asn_SPC_E_RABToBeModifiedItemBearerModIndIEs_specs_525	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P35_tags_36[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P35 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P35_tags_36,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P35_tags_36)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P35_tags_36[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P35_tags_36,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P35_tags_36)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P35_tags_36[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABNotToBeModifiedItemBearerModIndIEs_529,
	3,	/* Elements count */
	&asn_SPC_E_RABNotToBeModifiedItemBearerModIndIEs_specs_529	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P36_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P36 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P36_tags_37,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P36_tags_37)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P36_tags_37[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P36_tags_37,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P36_tags_37)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P36_tags_37[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABFailedToResumeItemResumeReqIEs_533,
	3,	/* Elements count */
	&asn_SPC_E_RABFailedToResumeItemResumeReqIEs_specs_533	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_ProtocolIE_SingleContainer_8146P37_tags_38[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_ProtocolIE_SingleContainer_8146P37 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_ProtocolIE_SingleContainer_8146P37_tags_38,
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P37_tags_38)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P37_tags_38[0]), /* 1 */
	asn_DEF_ProtocolIE_SingleContainer_8146P37_tags_38,	/* Same as above */
	sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P37_tags_38)
		/sizeof(asn_DEF_ProtocolIE_SingleContainer_8146P37_tags_38[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_E_RABFailedToResumeItemResumeResIEs_537,
	3,	/* Elements count */
	&asn_SPC_E_RABFailedToResumeItemResumeResIEs_specs_537	/* Additional specs */
};

