/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_SourceNodeID_H_
#define	_SourceNodeID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SourceNodeID_PR {
	SourceNodeID_PR_NOTHING,	/* No components present */
	SourceNodeID_PR_sourceNgRanNode_ID,
	SourceNodeID_PR_sourceNodeID_Extension
} SourceNodeID_PR;

/* Forward declarations */
struct SourceNgRanNode_ID;
struct SourceNodeID_Extension;

/* SourceNodeID */
typedef struct SourceNodeID {
	SourceNodeID_PR present;
	union SourceNodeID_u {
		struct SourceNgRanNode_ID	*sourceNgRanNode_ID;
		struct SourceNodeID_Extension	*sourceNodeID_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SourceNodeID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SourceNodeID;
extern asn_CHOICE_specifics_t asn_SPC_SourceNodeID_specs_1;
extern asn_TYPE_member_t asn_MBR_SourceNodeID_1[2];
extern asn_per_constraints_t asn_PER_type_SourceNodeID_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SourceNodeID_H_ */
#include <asn_internal.h>
