/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_SourceNodeID_Extension_H_
#define	_SourceNodeID_Extension_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-SingleContainer.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SourceNodeID-Extension */
typedef ProtocolIE_SingleContainer_8146P26_t	 SourceNodeID_Extension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SourceNodeID_Extension;
asn_struct_free_f SourceNodeID_Extension_free;
asn_struct_print_f SourceNodeID_Extension_print;
asn_constr_check_f SourceNodeID_Extension_constraint;
xer_type_decoder_f SourceNodeID_Extension_decode_xer;
xer_type_encoder_f SourceNodeID_Extension_encode_xer;
jer_type_encoder_f SourceNodeID_Extension_encode_jer;
per_type_decoder_f SourceNodeID_Extension_decode_aper;
per_type_encoder_f SourceNodeID_Extension_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SourceNodeID_Extension_H_ */
#include <asn_internal.h>
