/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_Time_UE_StayedInCell_EnhancedGranularity_H_
#define	_Time_UE_StayedInCell_EnhancedGranularity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Time-UE-StayedInCell-EnhancedGranularity */
typedef long	 Time_UE_StayedInCell_EnhancedGranularity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Time_UE_StayedInCell_EnhancedGranularity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Time_UE_StayedInCell_EnhancedGranularity;
asn_struct_free_f Time_UE_StayedInCell_EnhancedGranularity_free;
asn_struct_print_f Time_UE_StayedInCell_EnhancedGranularity_print;
asn_constr_check_f Time_UE_StayedInCell_EnhancedGranularity_constraint;
xer_type_decoder_f Time_UE_StayedInCell_EnhancedGranularity_decode_xer;
xer_type_encoder_f Time_UE_StayedInCell_EnhancedGranularity_encode_xer;
jer_type_encoder_f Time_UE_StayedInCell_EnhancedGranularity_encode_jer;
per_type_decoder_f Time_UE_StayedInCell_EnhancedGranularity_decode_aper;
per_type_encoder_f Time_UE_StayedInCell_EnhancedGranularity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Time_UE_StayedInCell_EnhancedGranularity_H_ */
#include <asn_internal.h>
