/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-PDU-Contents"
 * 	found in "r17.3.0/36413-h30.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps -no-gen-BER -no-gen-OER -no-gen-UPER -gen-XER`
 */

#ifndef	_UERadioCapabilityIDMappingResponse_H_
#define	_UERadioCapabilityIDMappingResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-Container.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* UERadioCapabilityIDMappingResponse */
typedef struct UERadioCapabilityIDMappingResponse {
	ProtocolIE_Container_8143P96_t	 protocolIEs;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UERadioCapabilityIDMappingResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UERadioCapabilityIDMappingResponse;
extern asn_SEQUENCE_specifics_t asn_SPC_UERadioCapabilityIDMappingResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_UERadioCapabilityIDMappingResponse_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _UERadioCapabilityIDMappingResponse_H_ */
#include <asn_internal.h>
